global:
  product: MyAwesomeProduct
  component: httpbin
  environment: production

image:
  name: docker.io/citizenstig/httpbin
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 8000

ingress:
  enabled: false
  name: ""
  path: ""

deployment:
  replicas:
    count: 1

resources:
  requests:
    memory: 64Mi
    cpu: 50m
  limits:
    memory: 64Mi
    cpu: 50m
