- name: Check PostgreSQL cluster status with pg_isready
  become: true
  become_user: postgres
  ansible.builtin.command:
    cmd: pg_isready
  register: pg_status
  changed_when: false

- name: Show PostgreSQL cluster status
  ansible.builtin.debug:
    msg: "{{ pg_status.stdout }}"
