- name: Configure PostgreSQL primary server
  hosts: primary
  become: true
  roles:
    - pg-primary

- name: Configure replica servers
  hosts: replicas
  become: true
  vars:
    primary_host: "{{ hostvars[groups['primary'][0]].ansible_host }}"
  roles:
    - pg-secondary-replica
