- name: Create PostgreSQL archive directory
  hosts: primary
  become: true
  tasks:
    - name: Create archive directory
      ansible.builtin.file:
        path: /var/lib/postgresql/14/main/archive
        state: directory
        owner: postgres
        group: postgres
        mode: "0700"

- name: Create replication user
  hosts: all
  become: true
  become_user: postgres
  tasks:
    - name: Create PostgreSQL Replicator User
      community.postgresql.postgresql_user:
        name: replicator
        password: "replicator_pass"
        role_attr_flags: REPLICATION
