- name: Install and configure Keepalived on VMs
  hosts: postgresql
  become: true
  roles:
    - vrrp-setup
  vars:
    keepalived_interface: ens33
    virtual_ip_address: 172.27.232.5
    vrrp_router_id: 51
    auth_pass: vrrp123456
