- name: Install PostgreSQL
  hosts: postgresql
  become: true
  roles:
    - pg-setup
  vars:
    postgres_version: "17"
    postgres_listen_address: "0.0.0.0"
    postgres_port: 5432
    pg_conf_dir: "/etc/postgresql/{{ postgres_version }}/main"

  handlers:
    - name: Restart PostgreSQL
      ansible.builtin.service:
        name: postgresql@{{ postgres_version }}-main
        state: restarted
