- name: Install PostgreSQL
  hosts: postgresql
  become: true
  roles:
    - pg-setup

  handlers:
    - name: Restart PostgreSQL
      ansible.builtin.service:
        name: postgresql@{{ postgres_version }}-main
        state: restarted
