- name: Install keepalived
  apt:
    name: keepalived
    state: present
    update_cache: true

- name: Deploy keepalived.conf
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: "0644"

- name: Enable and start keepalived
  systemd:
    name: keepalived
    state: started
    enabled: true