releases:
  - name: rktchat-app
    chart: .
    installed: true
    atomic: false
    cleanupOnFail: false
    kubeContext: ''
    createNamespace: true
    devel: false
    disableValidation: false
    disableValidationOnInstall: false
    disableOpenAPIValidation: false
    historyMax: 10
    skipDeps: false
    cascade: background
    insecureSkipTLSVerify: false
    timeout: 300
    recreatePods: false
    force: false
    wait: false
    waitForJobs: false
