- name: Create replication user
  become: true
  become_user: postgres
  ansible.builtin.shell: |
    psql -c "DO \$\$
    BEGIN
      IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '{{ replication_user }}') THEN
        CREATE ROLE {{ replication_user }} WITH REPLICATION LOGIN ENCRYPTED PASSWORD '{{ replication_password }}';
      END IF;
    END
    \$\$;"

- name: Restart PostgreSQL on primary
  ansible.builtin.service:
    name: postgresql@{{ postgres_version }}-main
    state: restarted
