- name: Configure postgresql.conf for replication
  ansible.builtin.blockinfile:
    path: /etc/postgresql/16/main/postgresql.conf
    block: |
      wal_level = replica
      max_wal_senders = 10
      max_replication_slots = 10
      hot_standby = on

- name: Configure pg_hba.conf for replication
  ansible.builtin.lineinfile:
    path: /etc/postgresql/16/main/pg_hba.conf
    line: 'host replication replicator 0.0.0.0/0 md5'
    state: present

- name: Restart PostgreSQL (Debian-style instance unit)
  ansible.builtin.service:
    name: postgresql@16-main.service
    state: restarted

- name: Create replicator user with replication privileges
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: replicator
    password: "repl123456"
    role_attr_flags: "LOGIN,REPLICATION"
    state: present
