apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-postgres
  namespace: keycloak
spec:
  instances: 3
  description: Postgres backend for keycloak.
  storage:
    storageClass: local-path
    size: "4Gi"
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      secret: 
        name: keycloak-postgresql-secret
  resources:
    limits:
      cpu: "2"
      memory: "4Gi"
    requests:
      cpu: "500m"
      memory: "1Gi"
