apiVersion: v1
kind: Secret
metadata:
  name: voteapp-postgresql-secret
  namespace: vote-app-ns
  labels:
    cnpg.io/reload: ""
type: kubernetes.io/basic-auth
data:
  password: dm90ZWFwcDEyMw==
  username: dm90ZWFwcA==
