kind: Service
apiVersion: v1
metadata:
  name: external-ip-database
spec:
  ports:
    - port: 3306
      targetPort: 3306
---
kind: Endpoints
apiVersion: v1
metadata:
  name: external-ip-database
subsets:
  - addresses:
      - ip: 185.204.170.125
    ports:
      - port: 3306
