apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard
  labels:
    app: kuard
    env: prod
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
    type: RollingUpdate
  revisionHistoryLimit: 14
  selector:
    matchLabels:
      app: kuard
      env: prod
  template:
    metadata:
      annotations:
        kubernetes.io/change-cause: "Update to blue version"
      labels:
        app: kuard
        env: prod
    spec:
      containers:
        - name: kuard
          image: "gcr.io/kuar-demo/kuard-amd64:blue"
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            periodSeconds: 2
            initialDelaySeconds: 0
            failureThreshold: 3
            successThreshold: 1
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kuard-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kuard
  minReplicas: 3
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: v1
kind: Service
metadata:
  name: kuard-prod
spec:
  type: ClusterIP
  selector:
    app: kuard
    env: prod
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: be-default
  labels:
    app: be-default
spec:
  rules:
  - host: kuard.kuberworks.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kuard-prod
            port:
              number: 8080
