apiVersion: batch/v1
kind: CronJob
metadata:
  name: example-cron
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: busyboxbatch-job
              image: busybox:1.36
              imagePullPolicy: IfNotPresent
              command: ["sh", "-c", "echo Hello from the test job! && sleep 2"]
          restartPolicy: OnFailure
