apiVersion: batch/v1
kind: Job
metadata:
  name: parallel
spec:
  parallelism: 5
  completions: 10
  template:
    metadata:
      labels:
        job: parallel
    spec:
      containers:
        - name: busybox
          image: busybox:1.36
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "echo Hello from the test job! && sleep 3"]
      restartPolicy: OnFailure
