apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpaca-prod
  namespace: sadeghns
  labels:
    app: alpaca
    env: prod
    ver: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpaca
      env: prod
      ver: "1"
  template:
    metadata:
      labels:
        app: alpaca
        env: prod
        ver: "1"
    spec:
      containers:
      - name: kuard
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          periodSeconds: 2
          initialDelaySeconds: 0
          failureThreshold: 3
          successThreshold: 1
        image: registry.sample.local/library/kuard:blue
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: alpaca-prod
  namespace: sadeghns
spec:
  type: LoadBalancer
  selector:
    app: alpaca
    env: prod
    ver: "1"
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

