apiVersion: v1
kind: Pod
metadata:
  name: kuard
spec:
  volumes:
    - name: tls-certs
      secret:
        secretName: kuard-tls
  containers:
    - image: gcr.io/kuar-demo/kuard-amd64:blue
      imagePullPolicy: Always
      name: kuard
      volumeMounts:
        - name: tls-certs
          mountPath: "/tls"
          readOnly: true
      envFrom:
        - configMapRef:
            name: my-config
      resources:
        requests:
          cpu: 500m
          memory: 128Mi
        limits:
          cpu: 1000m
          memory: 256Mi
      livenessProbe:
        httpGet:
          path: /healthy
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 5
        timeoutSeconds: 1
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /ready
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 5
        timeoutSeconds: 1
        failureThreshold: 3
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
