apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpaca-prod
  labels:
    app: alpaca
    env: prod
    ver: "1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alpaca
      env: prod
      ver: "1"
  template:
    metadata:
      labels:
        app: alpaca
        env: prod
        ver: "1"
    spec:
      containers:
      - name: kuard
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          periodSeconds: 2
          initialDelaySeconds: 0
          failureThreshold: 3
          successThreshold: 1
        image: gcr.io/kuar-demo/kuard-amd64:blue
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: alpaca-prod
spec:
  selector:
    app: alpaca
    env: prod
    ver: "1"
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpaca-test
  labels:
    app: alpaca
    env: test
    ver: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpaca
      env: test
      ver: "2"
  template:
    metadata:
      labels:
        app: alpaca
        env: test
        ver: "2"
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:green
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: alpaca-test
spec:
  type: NodePort
  selector:
    app: alpaca
    env: test
    ver: "2"
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bandicoot-prod
  labels:
    app: bandicoot
    env: prod
    ver: "2"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bandicoot
      env: prod
      ver: "2"
  template:
    metadata:
      labels:
        app: bandicoot
        env: prod
        ver: "2"
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:green
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: bandicoot-prod
spec:
  selector:
    app: bandicoot
    env: prod
    ver: "2"
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bandicoot-staging
  labels:
    app: bandicoot
    env: staging
    ver: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bandicoot
      env: staging
      ver: "2"
  template:
    metadata:
      labels:
        app: bandicoot
        env: staging
        ver: "2"
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:green
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: bandicoot-staging
spec:
  selector:
    app: bandicoot
    env: staging
    ver: "2"
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

