kind: Service
apiVersion: v1
metadata:
  namespace: sadeghns
  name: external-ip-minio
spec:
  ports:
    - port: 9000
      targetPort: 9000
---
kind: Endpoints
apiVersion: v1
metadata:
  namespace: sadeghns
  name: external-ip-minio
subsets:
  - addresses:
      - ip: 172.16.40.122
    ports:
      - port: 9000
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: sadeghns
  name: minio-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: s3.csi.k8s.io
    volumeHandle: minio-volume
    volumeAttributes:
      bucket: sadeghns
      region: us-east-1
      endpoint: https://external-ip-minio.sadeghns.svc.cluster.local
      storageClass: s3
      ssl: "false"
      secretName: s3-secret
      secretNamespace: sadeghns
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: sadeghns
  name: minio-pvc
spec:
  storageClassName: s3
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: minio-pv
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: sadeghns
type: Opaque
stringData:
  accessKeyID: 7oEFnsmSqqy9iUwQUxIC
  secretAccessKey: XqWhMNOFWnhP4k2A7cD67DP7F4YuzACb1tebkGj5

