- name: Stop PostgreSQL
  ansible.builtin.service:
    name: postgresql
    state: stopped

- name: Remove old data directory
  ansible.builtin.file:
    path: /var/lib/postgresql/16/main
    state: absent

- name: Clone data from primary
  ansible.builtin.command:
    cmd: "pg_basebackup -h {{ primary_host }} -D /var/lib/postgresql/16/main -U replicator -P -X stream"
    creates: /var/lib/postgresql/16/main
  environment:
    PGPASSWORD: repl123456
  register: clone_output
  ignore_errors: true

- name: Debug Clone Output
  ansible.builtin.debug:
    var: clone_output

- name: Configure recovery.conf
  ansible.builtin.copy:
    dest: /var/lib/postgresql/16/main/recovery.conf
    content: |
      standby_mode = 'on'
      primary_conninfo = 'host={{ primary_host }} port=5432 user=replicator password=repl123456'
      trigger_file = '/tmp/postgresql.trigger.5432'
    owner: postgres
    group: postgres
    mode: '0600'

- name: Start PostgreSQL
  ansible.builtin.service:
    name: postgresql
    state: started
