- name: Install Keepalived
  ansible.builtin.apt:
    name: keepalived
    state: present
    update_cache: true

- name: Enable and start Keepalived service
  ansible.builtin.service:
    name: keepalived
    enabled: true
    state: stopped

- name: Configure Keepalived
  ansible.builtin.copy:
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0644'
    content: |
      vrrp_instance VI_1 {
          state {{ vrrp_state }}
          interface {{ keepalived_interface }}
          virtual_router_id {{ vrrp_router_id }}
          priority {{ vrrp_priority }}
          advert_int 1

          authentication {
              auth_type PASS
              auth_pass {{ auth_pass }}
          }

          virtual_ipaddress {
              {{ virtual_ip_address }}
          }
      }

- name: Restart Keepalived to apply configuration
  ansible.builtin.service:
    name: keepalived
    state: restarted
